/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: carlin.chu (https://sketchfab.com/carlin.chu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-font-ade3845142dc4a3aa7c4e8a47f931109
Title: Cyberpunk Font
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function CyberpunkFont(props) {
  const { nodes, materials } = useGLTF('/models/cyberpunk_font.glb');
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.N_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.P_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.D_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.C_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.B_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.M_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.I_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.A_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.O_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.K_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Q_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.H_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.R_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.L_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.J_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.G_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.E_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.V_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.F_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.U_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Y_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.S_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.W_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Z_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.T_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.X_black_0 as any).geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.N_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.P_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.D_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.C_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.B_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.M_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.I_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.A_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.O_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.K_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Q_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.H_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.R_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.L_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.J_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.G_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.E_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.V_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.F_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.U_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Y_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.S_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.W_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Z_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.T_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.X_OL_Mtl_0 as any).geometry}
          material={materials.OL_Mtl}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/cyberpunk_font.glb');
